### ISSUE TITLE
Librefm support?

### ISSUE THREAD

**Issue by RockfordRoe** [joinemm/miso-bot#12]
Hello, I use libre.fm instead of last.fm because libre.fm does not claim ownership of my scrobbles and is a free alternative. Could there be a possibility of adding it in to the bot?

**Comment by joinemm** [comment]
Assuming libre.fm has an API with all the same functionality as last.fm, I still would have to rewrite everything to support that. And with such a low userbase compared to lastfm, I don't think there's many people who would even use it. So no, it's not going to happen anytime soon. 

Unless, someone else wants to do it. I would consider merging it to the bot.

**Comment by joinemm** [comment]
closing because I'm not going to add this.
