### ISSUE TITLE
Creation of colorchart doesn't work because of last.fm API bug

### ISSUE THREAD

**Issue by christian-lechner** [joinemm/miso-bot#23]
Hello,

I'm posting this on behalf of a user of your bot:

I came across this issue on the last.fm support forum: [Colorchart of Misobot doesn't work](https://support.last.fm/t/colorchart-misobot-doesnt-work/43365)

I saw in [lastfm.py#L777](https://github.com/joinemm/miso-bot/blob/bead29da5c3f3c4042001c476974edeb7207c119/cogs/lastfm.py#L777) that you are loading 1000 top albums of a user from the last.fm API. However, there is a bug in the last.fm API. If the limit is greater than 500, album art URLs will not be returned. 

If you set the limit to 500, your colorchart function should work again.

Best regards,
Christian

**Comment by joinemm** [comment]
Thanks for finding a workaround, this has been bothering me for a while. I was waiting for lastfm to fix this bug on their end but i guess they never will.

Colorchart fixed in commit 47f567c
