### ISSUE TITLE
">command list" limited to 10 pages, could you perhaps add a ">command export" feature?

### ISSUE THREAD

**Issue by Dejvi-Z** [joinemm/miso-bot#55]
It would make sense since there is already a ">command import" functionality.
My server has exceeded 10 pages of custom commands and it just says "+x more entries..." at the end of page 10. 
Currently in the process of cleaning up gfycat commands since the site is going down very soon.

**Comment by joinemm** [comment]
Good idea, i've implemented this in c746b19
