### ISSUE TITLE
YouTube command fails

### ISSUE THREAD

**Issue by Saragon4005** [joinemm/miso-bot#6]
Whenever the YouTube command is used the bot just returns `TypeError: 'NoneType' object is not iterable` error. After some research I think this might be caused by urls not being populated correctly in line 154 of /cogs/media.py

**Comment by joinemm** [comment]
After some debugging I have found the problem to be Youtube's API quota... which is kinda weird because I don't think I'm hitting it with the current usage

```
{'error': {
     'errors':  [{
        'domain': 'youtube.quota', 
        'reason': 'quotaExceeded', 
        'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.'
     }], 
     'code': 403, 
     'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.'
     }
}

**Comment by Saragon4005** [comment]
Searching youtube quota usage in Google got [this](https://developers.google.com/youtube/v3/getting-started#quota):
If you reach the quota limit, you can request additional quota on the [Quotas](https://console.developers.google.com/apis/api/youtube/quotas) tab in the Developer's Console.

So you can request more quota [here](https://console.developers.google.com/apis/api/youtube/quotas)

**Comment by joinemm** [comment]
I've submitted the request for additional quota. It might take a while for google to look at it though. Only thing to do now is wait unfortunately

**Comment by joinemm** [comment]
Good news, youtube finally got back to me and they have increased my quota by 10x
